version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./mysql:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:5.8.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$DB_NAME
    volumes:
      - ./wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.21-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      #- certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  #certbot:
  #  depends_on:
  #    - webserver
  #  image: certbot/certbot
  #  container_name: certbot
  #  volumes:
  #    - certbot-etc:/etc/letsencrypt
  #    - wordpress:/var/www/html
  #  command: certonly --webroot --webroot-path=/var/www/html --email sammy@example.com --agree-tos --no-eff-email --staging -d example.com -d www.example.com

volumes:
  #certbot-etc:
  wordpress:
  datadb:

networks:
  app-network: